### ISSUE TITLE
UI Bug Tracker

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#6107]
This issue tracks open bugs in the UI :

- [ ] As user : Does not refresh dashboard vlues when switching from a project to the default view 
- [ ] Launch VM and stay on page does not work
- [ ] Destroy instance expanded menu throws errors in the console
- [ ] Clear notification button remains when a notification is dismissed via the 'x' icon

**Comment by davidjumani** [comment]
@utchoang Can you please look into these ?

**Comment by utchoang** [comment]
@davidjumani I have created a PR. Can you please check the above error again?

**Comment by utchoang** [comment]
@davidjumani 
- Backup offerings is not visible from the Service offerings tab: I don't know where the service offering tab is located, can you be more specific?
- Assign VM to a backup offering button is missing: I check and it still shows up, maybe I got it wrong?
![image](https://user-images.githubusercontent.com/13766648/160038705-f0d69ac6-fe45-4243-b0e0-20c4a92f9127.png)

**Comment by slavkap** [comment]
Hi, @utchoang, I updated the issues, and in my UI (rebased on latest main), I don't see the Backup offerings
![image](https://user-images.githubusercontent.com/51903378/160066176-4e5d6684-88f5-4128-bece-6e0c0e346213.png)

I have it in my lab with 4.16.1.0
![image](https://user-images.githubusercontent.com/51903378/160066846-9e53326a-2672-4362-aa91-5611196a5c03.png)


And the VMs don't have this button you shared above ^^
![image](https://user-images.githubusercontent.com/51903378/160066300-32663c69-8cf9-4d18-b749-05ac20f303a4.png)

I'm probably doing something wrong

**Comment by utchoang** [comment]
@slavkap I running latest main branch with QA server then still show Backup Offerings. Can you check the permission of the user that is allowed to access `listBackupOfferings`?. 
![image](https://user-images.githubusercontent.com/13766648/160068565-703f283b-05af-442f-94d0-2c7c15cb4674.png)
And the button will show with `show: (record) => { return !record.backup offeringid }` condition. I think it only shows when the VM is not backup yet?
![image](https://user-images.githubusercontent.com/13766648/160069425-9eea5a01-1c1a-46cd-907a-5e451fe32313.png)

**Comment by slavkap** [comment]
I'm sorry @utchoang! I made some noise for nothing :( There is a configuration option that has to be enabled if you want to use the backup `backup.framework.enabled` (I forgot about it).

Again, sorry about it. Everything works.
