### ISSUE TITLE
UI - minor UI issues

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#6434]
##### ISSUE TYPE
 * Bug Report
 * Improvement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
main
~~~

- [x] When creating Primary storage and choosing a storage tag, the drop-down menu doesn't close
- [x] If you add a few tags, they are merged into one and cannot remove one of the listed -> #6438
- [x] If you add a new tag and select it, then try creating another tag and is truncated to the first character -> #6438
- [x] When Creating a Compute/Disk offering, the drop-down isn't closed also when you choose a zone. The same problem appears with the storage tags like the one on creating new Primary storage.
- [x] When you create a project and delete it from inside -> #6439
- [x] Creating volume from a snapshot with a custom disk offering  -> #6443
- [ ] Resizing DATA DISKs between 4.16.2 and 4.17 is not consistent
- [x] Deploy from ISO - hypervisor default value is empty -> #6436 

1: When creating Primary storage and choosing a storage tag, the drop-down menu doesn't close
![image](https://user-images.githubusercontent.com/51903378/171654856-037b42fb-9534-4bde-839f-88dc9dd8a802.png)

=====================
2: if you add a few tags, they are merged into one and cannot remove one of the listed 
![image](https://user-images.githubusercontent.com/51903378/171655971-a3e89e89-70ba-4307-a7ce-41350f31a626.png)

=====================
3: If you add a new tag and select it, then try creating another tag and is truncated to the first character
<img width="540" alt="Screen Shot 2022-06-02 at 12 18 15" src="https://user-images.githubusercontent.com/5295080/171663126-e49ac6f1-f105-4d41-bc43-8158893b7eda.png">

=====================
4: When Creating a Compute/Disk offering, the drop-down isn't closed also when you choose a zone. The same problem appears with the storage tags like the one on creating new Primary storage.

=====================

5: When you create a project and delete it from inside

![image](https://user-images.githubusercontent.com/51903378/171657546-ea02e379-802e-4ad9-9e86-db1d2d2da4c9.png)

=====================

6: Creating volume from a snapshot with a custom disk offering 

![image](https://user-images.githubusercontent.com/51903378/171658090-9673625a-ae2d-4fe3-a76b-bfdf8a9e8167.png)

=====================

7: Resizing DATA DISKs between 4.16.2 and 4.17 is not consistent (don't know which one is correct)

on 4.16.2.0

![image](https://user-images.githubusercontent.com/51903378/171660640-6ce1dc35-9346-4adc-81b9-8e50dda7cf24.png)

on 4.17 (RC4)
![image](https://user-images.githubusercontent.com/51903378/171660811-cd889a82-5926-47c4-ae10-b84127cda828.png)

**Comment by utchoang** [comment]
@slavkap `When creating Primary storage and choosing a storage tag, the drop-down menu doesn't close` -> This is multiple select mode, so the dropdown only closes when you lose focus or click outside.

**Comment by harikrishna-patnala** [comment]
@slavkap regarding the resize data disk UI form, this change is made as part of the new changes that went in 4.17 through PR#5008.

There is a detailed explanation of the feature changes made here https://cwiki.apache.org/confluence/display/CLOUDSTACK/Flexible+service+offerings (point no.4 in Design section)

From UI resize operation takes directly the size value, if the user wants to change the disk offering then there is a new button which triggers a new API to completely apply the disk offering properties.

Please let me know if this clarifies the change.

**Comment by slavkap** [comment]
Thanks, @utchoang, @harikrishna-patnala, for the explanations! 
@harikrishna-patnala, I wasn't aware of this change. Thanks for the link!
I'm closing the issue - everything is fixed, thanks!
