### ISSUE TITLE
Stabilize the smoke test on xcp-ng 81/82

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8586]
While testing #8497 , I found that there are some test failures with xcpng81/xcpng82, but not with xenserver-71

  - [x] fix test_guest_os (should be fixed by #8659)
  - [ ] fix test_cluster_drs (related to #7340)
  - [x] fix test_metrics_api (should be fixed by #8661)
  - [ ] fix test_non_affinity_group (related to #7340)
  - [x] fix test_register_userdata (related to #9244)
  - [x] fix test_vm_deployment_planner (related to #9244)
 

xcpng82
![image](https://github.com/apache/cloudstack/assets/57355700/fb7bf10b-9280-4615-95e8-d00127971e6b)

same errors with xcpng81

![image](https://github.com/apache/cloudstack/assets/57355700/19e8fbd8-64e2-4c6f-90b8-461dc053326c)

Most of these errors should happen in 4.19.0.0 as well.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.19+ debian12 (see #8497)

~~~

##### OS / ENVIRONMENT

xcpng81/xcpng82

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
same result of the health check PR
https://github.com/apache/cloudstack/pull/7344#issuecomment-1922893919
![image](https://github.com/apache/cloudstack/assets/57355700/706f9fa0-0369-43c5-8e14-365a08a04b42)

**Comment by weizhouapache** [comment]
closing this 
cc @DaanHoogland
